apiVersion:     v1
kind:           Secret

metadata:
    name:       mi-secret-1

data:
    variable1:  dmFsb3Ix
    variable2:  dmFsb3Iy
---
apiVersion:     v1
kind:           Secret

metadata:
    name:       mi-secret-2

data:
    variable_a:  dmFsb3Jh
    variable_b:  dmFsb3Ji
    variable_c:  dmFsb3Jj # Los valores van en BASE 64
---
apiVersion:     v1
kind:           Pod

metadata:
    name:       prueba-secret

spec:
    containers:
        -   name:       contenedor
            image:      ubuntu
            command:
                      - sleep
                      - "3600"
            envFrom: # Se usa menos
                - secretRef:
                    name:   mi-secret-1 # Todas las variables definidas en el secret traelas al contenedor, tal cual
                        # En mi contenedor tendré: variable1, variable2
            env:
                - name:     VARIABLE
                  value:    VALOR
                - name:     VAR_01
                  valueFrom:            # ESTO ES LO QUE MAS SE USA
                    secretKeyRef:
                        name:   mi-secret-2
                        key:    variable_a
                - name:     VAR_02
                  valueFrom:
                    secretKeyRef:
                        name:   mi-secret-2
                        key:    variable_b
                        # En este caso, del secret-2, solo traigo 2 variables...
                        # Y las renombro, al nombre que me interesa: variable_a -> VAR_01
                        #                                            variable_b -> VAR_02